//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.SoldItems = new HashSet<SoldItems>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public Nullable<int> itemCount { get; set; }
        public string itemDescription { get; set; }
        public Nullable<int> itemPrice { get; set; }
        public Nullable<double> itemDiscount { get; set; }
        public Nullable<int> itemManufacturerId { get; set; }
        public string itemImage { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<SoldItems> SoldItems { get; set; }
    }
}
