//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamDBEntities1 : DbContext
    {
        public ExamDBEntities1()
            : base("name=ExamDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Items> Items { get; set; }
        public DbSet<Manufacturers> Manufacturers { get; set; }
        public DbSet<orderGiveaway> orderGiveaway { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<orderStatuses> orderStatuses { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SoldItems> SoldItems { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
