//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderGiveaway
    {
        public orderGiveaway()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int placeId { get; set; }
        public string placeName { get; set; }
        public string placeAddress { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
