//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldItems
    {
        public int sellId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<int> orderId { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
